// vue/src/components/Label.vue
<script setup lang="ts">
    import type { PropType } from 'vue';
    import type { Field, Node } from '@/types'
    
    const {field} = defineProps({
        field: {
            type: Object as PropType<Node>,
            required: true
        }
    })
    const { decoration = '' } = field as Field
</script>

<template>
    <img v-if="decoration" :src="decoration"/>
    <h3 :id="field.id" v-html="field.label" />
</template>

<style scoped>
    h3 {
        margin-top: 1em;
        align-self: center;
    }
    img {
        max-height: 5em;
        max-width: 8em;
        width: auto;
        display: block;
        margin: 0 auto;
    }
</style>

// angular/src/app/label/label.component.ts
import { Component, Input } from '@angular/core'
import { emptyField } from '../shared/fields'
import { Node } from 'src/types'
@Component({
  selector: 'field-label',
  templateUrl: './label.component.html',
  styleUrls: ['./label.component.css'],
})
export class LabelComponent {
  constructor() {}

  @Input('field') field: Pick<Node, 'id' | 'label' | 'image'> = emptyField
}

<style>
    .image-box {
        display: flex;
        flex-direction: column;
        max-width: max-content;
        align-items: center;
    }
</style>

<label [for]="for">
    <div [ngClass]="{'image-box': !!image}">
        <img *ngIf="image" [src]="image" />
        <ng-content></ng-content>
    </div>
</label>
