// angular/src/app/authenticate/authenticate.component.ts
import { Component, Input, OnChanges, OnInit } from '@angular/core';
import { BowtieAuthSession, BowtieCredentials, authenticateSession } from '@youngalfred/bowtie-sdk';
import { Field, Fieldgroup } from 'src/types';

@Component({
  selector: 'authenticate',
  templateUrl: './authenticate.component.html',
  styleUrls: ['./authenticate.component.scss']
})
export class AuthenticateComponent {

  public email: string = ''
  public birthDate: string = ''
  get validEmail() { return this.email.length > 3 }
  get validISOPatternBday() {return  /[0-9]{4}-[0-9]{2}-[0-9]{2}/.test(this.birthDate) }
  get touched() {
    return {
      email: false,
      birthDate: false
    }
  }

  get disabled() {
    return this.fg.children.some(c => !(c as Field).valid?.valid)
  }

  get fg(): Fieldgroup {
    return {

      id: 'authentication-fg',
      kind: 'fieldgroup',
      label: 'To continue, please verify the email address and date of birth entered on your application.',
      classes: '',
      decoration: {},
      children: [
        {
          id: 'email',
          testId: 'authenticate-email',
          kind: 'text',
          label: 'Email Address',
          value: this.email,
          valid: { valid: this.validEmail, msg: this.touched.email ? 'Please enter a valid email' : '' }, 
          onChange: v => {
              this.email = v
              this.touched.email =true
          },
          classes: '',
        },
        {
            id: 'birthDate',
            kind: 'text',
            label: 'Birth Date (YYYY-MM-DD)',
            value: this.birthDate,
            testId: 'authenticate-email',
            valid:  { valid: this.validISOPatternBday, msg: this.touched.birthDate ? 'Please enter a valid birth date' : '' },
            onChange: v => {
                this.birthDate = v
                this.touched.birthDate = true
            },
            classes: '',
        }
      ],
    }
  }

  @Input('submit') submit?: (email: string, birthDate: string) => Promise<void>
  

  constructor() { }

  handleSubmit(e: Event) {
    e.preventDefault()

    const inputs = (e.target as HTMLFormElement).getElementsByTagName('input')
    const { email, birthDate } = Array.from(inputs).reduce((acc, next) => ({
        ...acc,
        [next.getAttribute('id') ?? '']: next.value
      }), {} as BowtieCredentials)
    
    this.submit?.(email, birthDate)
  }

}

<h2>Continue your application</h2>
<form (submit)="handleSubmit($event)">
    <renderer [node]="fg" depth="0"></renderer>
    <button type="submit" [disabled]="disabled">Submit</button>
</form>

// vue/src/views/Authenticate.vue
<script setup lang="ts">
import { reactive } from 'vue'
import NavBar from '@/components/NavBar.vue'
import Renderer from '@/components/Renderer.vue'
import router from '@/router'

import { usePortfolio } from '@/store/portfolio'
import type { Fieldgroup } from '@/types'


const store = usePortfolio()
const inputs = reactive({
    email: '',
    birthDate: '',
    touched: {email: false, birthDate: false}
})

// of course, you'd want to actually verify the input looks like an email here
const validEmail = inputs.email.length > 3
const validISOPatternBday = /[0-9]{4}-[0-9]{2}-[0-9]{2}/.test(inputs.birthDate)

const fg: Fieldgroup = {
    id: 'auth.fieldgroup',
    subtitle: '',
    warning: '',
    info: '',
    key: 'fg',
    valid: true,
    classes: [],
    kind: 'fieldgroup',
    label: 'To you continue your application, please validate the email and birth date on your application',
    children: [
        {
            id: 'authenticate.email',
            kind: 'text',
            label: 'Email Address',
            placeholder: 'Email',
            value: inputs.email,
            subtitle: '',
            info: '',
            warning: validEmail && inputs.touched.email ? 'Please enter a valid email' : '',
            decoration: '',
            valid: validEmail, 
            key: 'email',
            onChange: v => {
                inputs.email = v
                inputs.touched = {
                    ...inputs.touched,
                    email: true
                }
            },
            classes: [],
        },
        {
            id: 'authenticate.birthDate',
            kind: 'text',
            label: 'Birth Date',
            placeholder: 'YYYY-MM-DD',
            value: inputs.birthDate,
            subtitle: '',
            info: '',
            decoration: '',
            warning: validISOPatternBday && inputs.touched.birthDate ? 'Please enter a valid birth date' : '',
            valid: validISOPatternBday,
            key: 'birthDate',
            onChange: v => {
                inputs.birthDate = v
                inputs.touched = {
                    ...inputs.touched,
                    birthDate: true
                }
            },
            classes: [],
        }
    ]
}

const submit = async () => {
    const success = await store.authenticate(inputs.email, inputs.birthDate)
    if (success) {
        router.push('/')
    }
}

</script>

<template>
    <div id="wrapper">
      <h1>Authenticate</h1>
    <Renderer :key="fg.id" :field="fg" />
  </div>
  <NavBar
    :buttons="[
      {
        label: 'Submit',
        path: '/',
        onClick: submit,
        disabled: false,
      },
    ]"
  />
</template>

<style>
#wrapper {
  margin-bottom: 150px;
  padding: 2rem;
}
</style>
